// apps/web/src/routes/auth/register/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { authClient } from '$lib/auth-client';
  import Button from '$lib/components/ui/button.svelte';
  import Card from '$lib/components/ui/card.svelte';
  import Input from '$lib/components/ui/input.svelte';

  let email = $state('');
  let otp = $state('');
  let step = $state<'email' | 'otp' | 'passkey'>('email');
  let loading = $state(false);
  let error = $state('');

  async function sendOTP() {
    loading = true;
    error = '';
    try {
      const result = await authClient.emailOtp.sendVerificationOtp({ email, type: 'sign-in' });
      if (result.error) {
        error = result.error.message || 'Failed to send code';
      } else {
        step = 'otp';
      }
    } catch (e: any) {
      error = e.message || 'Failed to send code';
    } finally {
      loading = false;
    }
  }

  async function verifyOTP() {
    loading = true;
    error = '';
    try {
      const result = await authClient.signIn.emailOtp({ email, otp });
      if (result.error) {
        error = result.error.message || 'Invalid code';
      } else {
        step = 'passkey';
      }
    } catch (e: any) {
      error = e.message || 'Invalid code';
    } finally {
      loading = false;
    }
  }

  async function registerPasskey() {
    loading = true;
    error = '';
    try {
      const result = await authClient.passkey.addPasskey();
      if (result?.error) {
        error = result.error.message || 'Failed to register passkey';
      } else {
        goto('/dashboard');
      }
    } catch (e: any) {
      error = e.message || 'Failed to register passkey';
    } finally {
      loading = false;
    }
  }

  async function googleSignIn() {
    await authClient.signIn.social({ provider: 'google', callbackURL: `${window.location.origin}/auth/register?step=passkey` });
  }

  // Handle callback from Google OAuth
  import { page } from '$app/stores';
  import { onMount } from 'svelte';

  onMount(() => {
    const urlStep = $page.url.searchParams.get('step');
    if (urlStep === 'passkey') {
      step = 'passkey';
    }
  });
</script>

<div class="flex min-h-screen items-center justify-center bg-surface-50 px-4 py-12">
  <div class="w-full max-w-md">
    <!-- Logo mark -->
    <div class="mb-8 flex justify-center">
      <div class="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-surface-900">
        <svg class="h-6 w-6 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M21 2l-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m0 0l3 3L22 7l-3-3m-3.5 3.5L19 4" />
        </svg>
      </div>
    </div>

    <Card class="w-full">
      {#if step === 'email'}
        <h1 class="text-2xl font-bold text-surface-900 text-center mb-2">Create an account</h1>
        <p class="text-surface-500 text-center mb-6">Get started with OpenKey</p>

        {#if error}
          <div class="bg-red-50 border border-red-200 text-red-600 px-4 py-3 rounded-xl mb-6 text-sm" role="alert">
            {error}
          </div>
        {/if}

        <div class="flex flex-col gap-4">
          <form onsubmit={(e) => { e.preventDefault(); sendOTP(); }} class="flex flex-col gap-4">
            <div>
              <label for="email" class="sr-only">Email address</label>
              <Input
                id="email"
                type="email"
                bind:value={email}
                placeholder="Email address"
                required
                disabled={loading}
              />
            </div>
            <Button type="submit" disabled={loading} class="w-full">
              {loading ? 'Sending...' : 'Continue with Email'}
            </Button>
          </form>

          <div class="flex items-center gap-4 text-surface-400">
            <div class="flex-1 h-px bg-surface-200"></div>
            <span class="text-sm">or</span>
            <div class="flex-1 h-px bg-surface-200"></div>
          </div>

          <Button variant="secondary" onclick={googleSignIn} disabled={loading} class="w-full">
            Continue with Google
          </Button>

          <p class="text-center text-sm text-surface-500 mt-2">
            Already have an account? <a href="/auth/login" class="text-surface-900 font-medium hover:underline">Sign in</a>
          </p>
        </div>
      {/if}

      {#if step === 'otp'}
        <h1 class="text-2xl font-bold text-surface-900 text-center mb-2">Check your email</h1>
        <p class="text-surface-500 text-center mb-6">
          Enter the 6-digit code sent to <span class="text-surface-900 font-medium">{email}</span>
        </p>

        {#if error}
          <div class="bg-red-50 border border-red-200 text-red-600 px-4 py-3 rounded-xl mb-6 text-sm" role="alert">
            {error}
          </div>
        {/if}

        <form onsubmit={(e) => { e.preventDefault(); verifyOTP(); }} class="flex flex-col gap-4">
          <div>
            <label for="otp" class="sr-only">Verification code</label>
            <Input
              id="otp"
              type="text"
              bind:value={otp}
              placeholder="000000"
              maxlength={6}
              inputmode="numeric"
              autocomplete="one-time-code"
              required
              disabled={loading}
              class="text-center text-2xl tracking-widest font-mono"
            />
          </div>
          <Button type="submit" disabled={loading} class="w-full">
            {loading ? 'Verifying...' : 'Verify'}
          </Button>
        </form>
        <Button variant="ghost" onclick={() => { step = 'email'; error = ''; }} class="w-full mt-2">
          Back
        </Button>
      {/if}

      {#if step === 'passkey'}
        <h1 class="text-2xl font-bold text-surface-900 text-center mb-2">Set up your passkey</h1>
        <p class="text-surface-500 text-center mb-6">
          Passkeys are the most secure way to sign in. You'll use this instead of a password.
        </p>

        {#if error}
          <div class="bg-red-50 border border-red-200 text-red-600 px-4 py-3 rounded-xl mb-6 text-sm" role="alert">
            {error}
          </div>
        {/if}

        <div class="flex flex-col gap-4">
          <Button onclick={registerPasskey} disabled={loading} class="w-full">
            {loading ? 'Registering...' : 'Register Passkey'}
          </Button>
        </div>
      {/if}
    </Card>
  </div>
</div>

// project/frontend/src/app/auth/register/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/app/providers';
import { WebAuthnClient } from '@/lib/webauthn';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Shield, Fingerprint, AlertCircle, CheckCircle } from 'lucide-react';

export default function RegisterPage() {
  const [email, setEmail] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const [step, setStep] = useState<'email' | 'webauthn' | 'success'>('email');
  const { login } = useAuth();
  const router = useRouter();

  const handleEmailSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!email) {
      setError('Email is required');
      return;
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      setError('Please enter a valid email address');
      return;
    }

    // Check WebAuthn support
    if (!WebAuthnClient.isSupported()) {
      setError('WebAuthn is not supported on this device or browser. Please use a modern browser with HTTPS.');
      return;
    }

    setError('');
    setStep('webauthn');
  };

  const handleWebAuthnRegister = async () => {
    setIsLoading(true);
    setError('');

    try {
      const { user, token } = await WebAuthnClient.register(email);
      
      // Store auth data
      login(user, token);
      
      setStep('success');
      
      // Redirect to dashboard after a moment
      setTimeout(() => {
        router.push('/dashboard');
      }, 2000);
      
    } catch (error) {
      console.error('Registration error:', error);
      setError(WebAuthnClient.formatError(error));
    } finally {
      setIsLoading(false);
    }
  };

  const goBack = () => {
    if (step === 'webauthn') {
      setStep('email');
    } else {
      router.push('/');
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="flex justify-center mb-4">
            <Shield className="h-12 w-12 text-indigo-600" />
          </div>
          <h1 className="text-3xl font-bold text-gray-900">Create Account</h1>
          <p className="text-gray-600 mt-2">
            Get started with OpenKey's secure authentication
          </p>
        </div>

        <Card>
          <CardHeader className="text-center">
            <CardTitle>
              {step === 'email' && 'Enter Your Email'}
              {step === 'webauthn' && 'Set Up Passkey'}
              {step === 'success' && 'Account Created!'}
            </CardTitle>
            <CardDescription>
              {step === 'email' && 'We\'ll use this to create your secure account'}
              {step === 'webauthn' && 'Use your device\'s biometrics or security key'}
              {step === 'success' && 'Welcome to OpenKey! Redirecting...'}
            </CardDescription>
          </CardHeader>

          <CardContent className="space-y-6">
            {/* Email Step */}
            {step === 'email' && (
              <form onSubmit={handleEmailSubmit} className="space-y-4">
                <div>
                  <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-2">
                    Email Address
                  </label>
                  <input
                    type="email"
                    id="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
                    placeholder="you@example.com"
                    required
                  />
                </div>
                
                <Button type="submit" className="w-full">
                  Continue
                </Button>
              </form>
            )}

            {/* WebAuthn Step */}
            {step === 'webauthn' && (
              <div className="text-center space-y-6">
                <div className="bg-indigo-50 rounded-lg p-6">
                  <Fingerprint className="h-16 w-16 text-indigo-600 mx-auto mb-4" />
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">
                    Secure Your Account
                  </h3>
                  <p className="text-gray-600 text-sm">
                    Use your device's built-in security features like Face ID, Touch ID, 
                    or Windows Hello to protect your account.
                  </p>
                </div>

                <Button
                  onClick={handleWebAuthnRegister}
                  disabled={isLoading}
                  className="w-full"
                  size="lg"
                >
                  {isLoading ? (
                    <div className="flex items-center">
                      <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                      Creating Passkey...
                    </div>
                  ) : (
                    'Create Passkey'
                  )}
                </Button>

                <p className="text-xs text-gray-500">
                  You'll be prompted to use your device's authentication method
                </p>
              </div>
            )}

            {/* Success Step */}
            {step === 'success' && (
              <div className="text-center space-y-6">
                <div className="bg-green-50 rounded-lg p-6">
                  <CheckCircle className="h-16 w-16 text-green-600 mx-auto mb-4" />
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">
                    Account Created Successfully!
                  </h3>
                  <p className="text-gray-600 text-sm">
                    Your OpenKey account is ready. You'll be redirected to your dashboard.
                  </p>
                </div>
                
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600 mx-auto"></div>
              </div>
            )}

            {/* Error Display */}
            {error && (
              <div className="bg-red-50 border border-red-200 rounded-md p-4">
                <div className="flex">
                  <AlertCircle className="h-5 w-5 text-red-400" />
                  <div className="ml-3">
                    <p className="text-sm text-red-800">{error}</p>
                  </div>
                </div>
              </div>
            )}

            {/* Navigation */}
            <div className="flex justify-between items-center pt-4">
              <Button variant="ghost" onClick={goBack}>
                ← Back
              </Button>
              
              <Button
                variant="link"
                onClick={() => router.push('/auth/login')}
                className="text-sm"
              >
                Already have an account? Sign in
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
